import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';
import logo from '../assets/alignRFP_logo7.svg';

const TermsOfService: React.FC = () => {
  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-green-50">
      {/* Navbar */}
      <nav className="bg-white shadow-soft py-4">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between">
            <Link to="/" className="flex items-center text-2xl font-bold no-underline whitespace-nowrap">
              <img src={logo} alt="AlignRFP logo" className="h-8 w-8 mr-2" />
              <span className="font-sans text-charcoal-900">AlignRFP</span>
            </Link>
            <Link 
              to="/" 
              className="flex items-center gap-2 text-charcoal-600 hover:text-primary-500 transition-colors duration-200"
            >
              <ArrowLeft size={20} />
              Back to Home
            </Link>
          </div>
        </div>
      </nav>

      <div className="max-w-4xl mx-auto py-12 px-4 sm:px-6 lg:px-8">
        <header className="mb-10 text-center">
          <h1 className="text-4xl md:text-5xl font-bold text-charcoal-900 tracking-tight mb-4">Terms of Service</h1>
          <p className="text-lg text-charcoal-600">Last updated: February 15, 2026</p>
        </header>
        
        <div className="bg-white shadow-strong rounded-2xl p-8 md:p-12 prose prose-lg prose-charcoal max-w-none">
          <p className="text-charcoal-700 leading-relaxed">
            Please read these Terms of Service ("Terms", "Terms of Service") carefully before using the AlignRFP website and application (the "Service") operated by AlignRFP ("us", "we", or "our").
          </p>
          <p className="text-charcoal-700 leading-relaxed">
            Your access to and use of the Service is conditioned on your acceptance of and compliance with these Terms. These Terms apply to all visitors, users, and others who access or use the Service.
          </p>
          <p className="text-charcoal-700 leading-relaxed">
            By accessing or using the Service you agree to be bound by these Terms. If you disagree with any part of the terms then you may not access the Service.
          </p>

          <h2 className="text-2xl font-bold text-charcoal-900 mt-12 mb-6 border-b border-charcoal-200 pb-2">1. Accounts</h2>
          <p className="text-charcoal-700 leading-relaxed">When you create an account with us, you must provide us information that is accurate, complete, and current at all times. Failure to do so constitutes a breach of the Terms, which may result in immediate termination of your account on our Service.</p>
          <p className="text-charcoal-700 leading-relaxed">You are responsible for safeguarding the password that you use to access the Service and for any activities or actions under your password, whether your password is with our Service or a third-party service.</p>
          <p className="text-charcoal-700 leading-relaxed">You agree not to disclose your password to any third party. You must notify us immediately upon becoming aware of any breach of security or unauthorized use of your account.</p>

          <h2 className="text-2xl font-bold text-charcoal-900 mt-12 mb-6 border-b border-charcoal-200 pb-2">2. Intellectual Property</h2>
          <p className="text-charcoal-700 leading-relaxed">The Service and its original content (excluding Content provided by users), features and functionality are and will remain the exclusive property of AlignRFP and its licensors. The Service is protected by copyright, trademark, and other laws of both the United States and foreign countries.</p>
          <p className="text-charcoal-700 leading-relaxed">Our trademarks and trade dress may not be used in connection with any product or service without the prior written consent of AlignRFP.</p>
          <p className="text-charcoal-700 leading-relaxed">As an AI-powered RFP Response Generation and Management tool, AlignRFP processes user-provided content ("User Content") to generate RFP responses. You retain all rights to your User Content. By using the Service, you grant AlignRFP a non-exclusive, worldwide, royalty-free license to use, reproduce, modify, and process your User Content solely for the purpose of providing and improving the Service. We will not use your User Content for any other purpose without your explicit consent.</p>
          <p className="text-charcoal-700 leading-relaxed">Generated RFP responses are owned by you. However, AlignRFP is not responsible for the accuracy, legality, or compliance of the generated content. You are solely responsible for reviewing and ensuring the suitability of any content generated by the Service before use.</p>

          <h2 className="text-2xl font-bold text-charcoal-900 mt-12 mb-6 border-b border-charcoal-200 pb-2">3. User Conduct</h2>
          <p className="text-charcoal-700 leading-relaxed">You agree not to use the Service:</p>
          <ul className="list-disc list-inside space-y-2 text-charcoal-700 ml-4">
            <li>In any way that violates any applicable national or international law or regulation.</li>
            <li>For the purpose of exploiting, harming, or attempting to exploit or harm minors in any way by exposing them to inappropriate content or otherwise.</li>
            <li>To transmit, or procure the sending of, any advertising or promotional material, including any "junk mail," "chain letter," "spam," or any other similar solicitation.</li>
            <li>To impersonate or attempt to impersonate AlignRFP, an AlignRFP employee, another user, or any other person or entity.</li>
            <li>In any way that infringes upon the rights of others, or in any way is illegal, threatening, fraudulent, or harmful, or in connection with any unlawful, illegal, fraudulent, or harmful purpose or activity.</li>
            <li>To engage in any other conduct that restricts or inhibits anyone's use or enjoyment of the Service, or which, as determined by us, may harm or offend AlignRFP or users of the Service or expose them to liability.</li>
          </ul>
          <p className="text-charcoal-700 leading-relaxed">Additionally, you agree not to:</p>
          <ul className="list-disc list-inside space-y-2 text-charcoal-700 ml-4">
            <li>Use the Service in any manner that could disable, overburden, damage, or impair the Service or interfere with any other party's use of the Service.</li>
            <li>Use any robot, spider, or other automatic device, process, or means to access the Service for any purpose, including monitoring or copying any of the material on the Service.</li>
            <li>Introduce any viruses, trojan horses, worms, logic bombs, or other material which is malicious or technologically harmful.</li>
            <li>Attempt to gain unauthorized access to, interfere with, damage, or disrupt any parts of the Service, the server on which the Service is stored, or any server, computer, or database connected to the Service.</li>
          </ul>

          <h2 className="text-2xl font-bold text-charcoal-900 mt-12 mb-6 border-b border-charcoal-200 pb-2">4. Service Plans and Usage Limits</h2>
          <p className="text-charcoal-700 leading-relaxed">AlignRFP offers tiered service plans, each with defined usage limits. By subscribing to a plan, you agree to operate within the usage limits associated with your selected tier.</p>

          <h3 className="text-xl font-semibold text-charcoal-800 mt-8 mb-4">Active Proposals</h3>
          <p className="text-charcoal-700 leading-relaxed">Each plan includes a limit on the number of active proposals you may maintain at any given time. Active proposals are those currently in progress or open for editing. You may archive or mark proposals as complete at any time, at which point they become view-only and no longer count toward your active proposal limit.</p>
          <ul className="list-disc list-inside space-y-2 text-charcoal-700 ml-4">
            <li><strong>Starter:</strong> Up to 10 active proposals per month</li>
            <li><strong>Pro:</strong> Up to 50 active proposals per month</li>
            <li><strong>Enterprise:</strong> Unlimited active proposals</li>
          </ul>

          <h3 className="text-xl font-semibold text-charcoal-800 mt-8 mb-4">Archived Proposals</h3>
          <p className="text-charcoal-700 leading-relaxed">Archived and completed proposals remain accessible in a view-only state. To ensure fair use of platform resources, each plan includes a soft limit on the total number of archived proposals stored on your account:</p>
          <ul className="list-disc list-inside space-y-2 text-charcoal-700 ml-4">
            <li><strong>Starter:</strong> Up to 500 archived proposals</li>
            <li><strong>Pro:</strong> Up to 5,000 archived proposals</li>
            <li><strong>Enterprise:</strong> Custom limits based on your agreement</li>
          </ul>
          <p className="text-charcoal-700 leading-relaxed">If you approach or exceed your archived proposal limit, we may ask you to remove older archived proposals or upgrade your plan. We reserve the right to enforce these limits to maintain the quality and performance of the Service for all users.</p>

          <h3 className="text-xl font-semibold text-charcoal-800 mt-8 mb-4">Plan Changes</h3>
          <p className="text-charcoal-700 leading-relaxed">You may upgrade or downgrade your plan at any time. If you downgrade to a plan with lower limits, existing archived proposals beyond the new limit will remain accessible in view-only mode, but you will not be able to create new proposals until your usage is within the limits of your current plan.</p>

          <h2 className="text-2xl font-bold text-charcoal-900 mt-12 mb-6 border-b border-charcoal-200 pb-2">5. Termination</h2>
          <p className="text-charcoal-700 leading-relaxed">We may terminate or suspend your account and bar access to the Service immediately, without prior notice or liability, under our sole discretion, for any reason whatsoever and without limitation, including but not limited to a breach of the Terms.</p>
          <p className="text-charcoal-700 leading-relaxed">If you wish to terminate your account, you may simply discontinue using the Service.</p>
          <p className="text-charcoal-700 leading-relaxed">All provisions of the Terms which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity and limitations of liability.</p>

          <h2 className="text-2xl font-bold text-charcoal-900 mt-12 mb-6 border-b border-charcoal-200 pb-2">6. Disclaimer of Warranties; Limitation of Liability</h2>
          <p className="text-charcoal-700 leading-relaxed">The Service is provided on an "AS IS" and "AS AVAILABLE" basis. AlignRFP makes no representations or warranties of any kind, express or implied, as to the operation of their services, or the information, content, or materials included therein. You expressly agree that your use of these services, their content, and any services or items obtained from us is at your sole risk.</p>
          <p className="text-charcoal-700 leading-relaxed">Neither AlignRFP nor any person associated with AlignRFP makes any warranty or representation with respect to the completeness, security, reliability, quality, accuracy, or availability of the services. Without limiting the foregoing, neither AlignRFP nor anyone associated with AlignRFP represents or warrants that the services, their content, or any services or items obtained through the services will be accurate, reliable, error-free, or uninterrupted, that defects will be corrected, that the services or the server that makes it available are free of viruses or other harmful components or that the services or any services or items obtained through the services will otherwise meet your needs or expectations.</p>
          <p className="text-charcoal-700 leading-relaxed">AlignRFP hereby disclaims all warranties of any kind, whether express or implied, statutory, or otherwise, including but not limited to any warranties of merchantability, non-infringement, and fitness for particular purpose.</p>
          <p className="text-charcoal-700 leading-relaxed">In no event will AlignRFP, its affiliates, or their licensors, service providers, employees, agents, officers, or directors be liable for damages of any kind, under any legal theory, arising out of or in connection with your use, or inability to use, the Service, any websites linked to it, any content on the Service or such other websites, including any direct, indirect, special, incidental, consequential, or punitive damages, including but not limited to, personal injury, pain and suffering, emotional distress, loss of revenue, loss of profits, loss of business or anticipated savings, loss of use, loss of goodwill, loss of data, and whether caused by tort (including negligence), breach of contract, or otherwise, even if foreseeable.</p>

          <h2 className="text-2xl font-bold text-charcoal-900 mt-12 mb-6 border-b border-charcoal-200 pb-2">7. Governing Law</h2>
          <p className="text-charcoal-700 leading-relaxed">These Terms shall be governed and construed in accordance with the laws of the United States, without regard to its conflict of law provisions.</p>
          <p className="text-charcoal-700 leading-relaxed">Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights. If any provision of these Terms is held to be invalid or unenforceable by a court, the remaining provisions of these Terms will remain in effect. These Terms constitute the entire agreement between us regarding our Service, and supersede and replace any prior agreements we might have had between us regarding the Service.</p>

          <h2 className="text-2xl font-bold text-charcoal-900 mt-12 mb-6 border-b border-charcoal-200 pb-2">8. Changes</h2>
          <p className="text-charcoal-700 leading-relaxed">We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material we will provide at least 30 days' notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.</p>
          <p className="text-charcoal-700 leading-relaxed">By continuing to access or use our Service after any revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, you are no longer authorized to use the Service.</p>

          <h2 className="text-2xl font-bold text-charcoal-900 mt-12 mb-6 border-b border-charcoal-200 pb-2">9. Contact Us</h2>
          <p className="text-charcoal-700 leading-relaxed">If you have any questions about these Terms, please contact us:</p>
          <ul className="list-disc list-inside space-y-2 text-charcoal-700 ml-4">
            <li>By email: <a href="mailto:support@alignrfp.com" className="text-primary-600 hover:text-primary-700 underline transition-colors duration-200">support@alignrfp.com</a></li>
          </ul>
        </div>
      </div>
    </div>
  );
};

export default TermsOfService;